### PR TITLE
Feat run cmd on cluster

### PR DESCRIPTION
**Pull request by ronaknnathani**

### CODE REVIEW

**Comment by ronaknnathani** [comment]
@aouyang1 have you enabled Tracis CI for Pegasus?

**Comment by aouyang1** [comment]
ah yes this was a test. I'm disabling it now. I think for now we'll keep on using jenkins.

test this please

**Comment by aouyang1** [comment]
This looks good to me. Have you considered with the peg command will be for this? I figure you'd want to just add this in as well.

**Comment by ronaknnathani** [comment]
Hmm...haven't considered the peg command as it is one of the utilities. I am using it just by sourcing util.sh but I guess having a generic command for some util.sh functions would be good - like `run_cmd_on_node` and `run_cmd_on_cluster`.

How about `peg util <function-name> <args>`? For now, we can allow only two commands `run_cmd_on_node` and `run_cmd_on_cluster`

**Comment by aouyang1** [comment]
There's already a `peg sshcmd <clustername> <number> <cmd>`. maybe if the number is left out then we do it to the entire cluster?

**Comment by ronaknnathani** [comment]
Yeah! that'd work. I think there should still be one command for just a node in addition to the command for a cluster.

May be for the cluster it could be `peg sshcmd-cluster <clustername> <cmd>`?

**Comment by aouyang1** [comment]
So option based in `peg sshcmd` and also a separate peg command `peg sshcmd-cluster`?

**Comment by ronaknnathani** [comment]
Yeah! So that a cmd can be executed on any particular node as well as on the entire cluster if needed.

**Comment by aouyang1** [comment]
I feel like the option in peg sshcmd would be redundant right?

single node: `peg sshcmd my-cluster 1 'sudo apt-get install python3'
multi-node: `peg sshcmd my-cluster 'sudo apt-get install python3'

vs 

multi-node: peg sshcmd-cluster my-cluster 'sudo apt-get install python3'

**Comment by ronaknnathani** [comment]
Yeah it'd be redundant in the case you mentioned but I was thinking about what if some commands are to be executed only on a particular node, like, maybe master node. What do you think?

**Comment by aouyang1** [comment]
`peg sshcmd my-cluster 1 'sudo apt-get install python3'` does it only on master right?

`peg sshcmd my-cluster 1 'sudo apt-get install python3'` would only operate on the 1st worker node

**Comment by ronaknnathani** [comment]
`peg sshcmd my-cluster 1 'sudo apt-get install python3'` would work on master for techs which have a master and 1st node for techs which don't have a master.

**Comment by aouyang1** [comment]
Yeah. I don't think I'm quite following what your first comment about "executed only on a particular node, like, maybe master node" since I feel peg sshcmd 1 does that?

**Comment by ronaknnathani** [comment]
I just meant that we can have two different peg commands
* one to run a cmd on any one node of the cluster 
     `peg sshcmd <cluster-name> <number> <cmd>`
* one to run a cmd on all nodes of the cluster
     `peg sshcmd-cluster <cluster-name> <cmd>`

does that make sense?

**Comment by aouyang1** [comment]
Yeah that does. I was debating that we merge the sshcmd-cluster into sshcmd since it's quite related. Not sure what's more intuitive for users. We should probably go with sshcmd-cluster for now since it requires the least amount of logic.

**Comment by ronaknnathani** [comment]
In that case, how about making it something like as follows?
* `peg sshcmd-cluster <cluster-name> <cmd>`
* `peg sshcmd-node <cluster-name> <number> <cmd>`

**Comment by aouyang1** [comment]
Yeah that looks like a good plan. Can you also check to see if sshcmd is used in any other scripts? Don't want to break anything if we change the pegasus api.

**Comment by ronaknnathani** [comment]
Sure! I'll check that.

**Comment by ronaknnathani** [comment]
Added sshcmd-cluster and updated sshcmd -> sshcmd-node

**Comment by aouyang1** [comment]
test this please

**Comment by aouyang1** [comment]
Looks go to me. Let me know if you've tested out the memsql install which uses the peg sshcmd-node. If so, I'll go ahead and merge.

**Comment by ronaknnathani** [comment]
Haven't tested the memsql installation, I just checked the `sshcmd-node` by itself and it worked fine.

**Comment by aouyang1** [comment]
alright. I'll give it a shot just as a sanity check. Want to make sure the memsql install hasn't been broken.

**Comment by ronaknnathani** [comment]
Sounds good!

**Comment by aouyang1** [comment]
Memsql checked out. merging

**Pull request merged**
