### PR TITLE
Augmented Hadoop classpath to allow s3a commands such as distcp to work

### PR DESCRIPTION
**Pull request by emhoa**
Hadoop has some libraries that must be manually added to the classpath before s3a commands, such as distcp, can work. Updates made to hadoop-env.sh and mapred-site.xml

### CODE REVIEW

**Comment by aouyang1** [comment]
@emhoa Sorry to get back so late. This is great! Could you also test this with Spark to make sure that we can still talk with s3 using the s3a protocol?

**Comment by emhoa** [comment]
Hey @aouyang1 Sorry for the late reply but after testing this for Spark, I found some more bugs that I just fixed with the spark setup_single.sh script and committed to this branch. Let me know if you have any questions or concerns.

**Comment by aouyang1** [comment]
@emhoa Great! I'll test out hadoop and spark as well and see if things are good too. Does spark not make a lib directory by default or is that a spark 2.0 thing?

**Comment by aouyang1** [comment]
@emhoa I checked out the branch and it looks like Spark can't read using the s3a endpoint now. This change I assume is so that Hadoop can read from s3a?

**Comment by emhoa** [comment]
I don't believe Spark has a lib directory, at least not at that top level but I'd have to look at it some more.


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------
From: Austin Ouyang
Date:10/25/2016 7:32 PM (GMT-05:00)
To: InsightDataScience/pegasus
Cc: Hoa Nguyen , Mention
Subject: Re: [InsightDataScience/pegasus] Augmented Hadoop classpath to allow s3a commands such as distcp to work (#108)


@emhoa<https://github.com/emhoa> Great! I'll test out hadoop and spark as well and see if things are good too. Does spark not make a lib directory by default or is that a spark 2.0 thing?

-

**Comment by emhoa** [comment]
Sorry, I'm not sure what you're asking. S3a is working with this branch...it wasn't before. I did point the Spark classpath to where the HDFS config files are stored in order to pick up the AWS credentials that you'll need to access the buckets. In thinking about it some more, where it might not work is when spark is installed but not hadoop. Can think about how to get around it some more.


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------
From: Austin Ouyang
Date:10/25/2016 8:20 PM (GMT-05:00)
To: InsightDataScience/pegasus
Cc: Hoa Nguyen , Mention
Subject: Re: [InsightDataScience/pegasus] Augmented Hadoop classpath to allow s3a commands such as distcp to work (#108)


@emhoa<https://github.com/emhoa> I checked out the branch and it looks like Spark can't read using the s3a endpoint now. This change I assume is so that Hadoop can read from s3a?

-

**Comment by aouyang1** [comment]
test this please

**Pull request merged**
